// src/types/card.ts
// ---------------------------------------------------------------------------
// Core card record — represents a single flashcard persisted in the store.
// Every card has an `id` (the ^sprout-XXXXXXXXX anchor), a `type` that
// determines which fields are relevant, and a `sourceNotePath` pointing
// back to the Obsidian note it was parsed from.
// ---------------------------------------------------------------------------

/** All supported card formats, including child types generated by sync. */
export type CardRecordType = "basic" | "mcq" | "cloze" | "cloze-child" | "io" | "io-child";

/**
 * Persistent record for a single flashcard.
 *
 * Fields are grouped by card type — only the fields relevant to a given
 * `type` are populated; the rest are `undefined` or `null`.
 */
export type CardRecord = {
  id: string;
  type: CardRecordType;
  title: string | null;

  // ── Basic ──────────────────────────────────────────────────────────────
  q?: string | null;
  a?: string | null;

  // ── Multiple Choice (MCQ) ──────────────────────────────────────────────
  stem?: string | null;
  options?: string[] | null;
  correctIndex?: number | null;

  // ── Cloze ──────────────────────────────────────────────────────────────
  clozeText?: string | null;
  clozeChildren?: number[] | null;
  clozeIndex?: number | null;

  // ── Image Occlusion (IO) — shared ─────────────────────────────────────
  /** Optional question prompt written inside an IO block. */
  prompt?: string | null;

  // ── IO parent ──────────────────────────────────────────────────────────
  imageRef?: string | null;
  /** @deprecated Alias for `imageRef`; kept for backwards-compat with older stores. */
  ioSrc?: string | null;
  maskMode?: "solo" | "all" | null;

  // ── IO child ───────────────────────────────────────────────────────────
  parentId?: string;
  groupKey?: string;
  rectIds?: string[];
  retired?: boolean;

  // ── Shared metadata ────────────────────────────────────────────────────
  info?: string | null;
  groups?: string[] | null;

  // ── Source location ────────────────────────────────────────────────────
  sourceNotePath: string;
  sourceStartLine: number;

  // ── Bookkeeping (written by sync; optional for older stores) ───────────
  createdAt?: number;
  updatedAt?: number;
  lastSeenAt?: number;
};
