/**
 * @file src/types/card.ts
 * @summary Core card record types. Defines CardRecordType (the supported card formats:
 * basic, mcq, cloze, cloze-child, io, io-child) and the full CardRecord shape that
 * represents a single flashcard persisted in the store, including fields for every card
 * type, source-location metadata, image-occlusion data, and legacy backward-compat aliases.
 *
 * @exports
 *   - CardRecordType — union type of all supported card format identifiers
 *   - CardRecord — type for a single persistent flashcard record
 */

/** All supported card formats, including child types generated by sync. */
export type CardRecordType = "basic" | "mcq" | "cloze" | "cloze-child" | "io" | "io-child";

/**
 * Persistent record for a single flashcard.
 *
 * Fields are grouped by card type — only the fields relevant to a given
 * `type` are populated; the rest are `undefined` or `null`.
 */
export type CardRecord = {
  id: string;
  type: CardRecordType;
  title: string | null;

  // ── Basic ──────────────────────────────────────────────────────────────
  q?: string | null;
  a?: string | null;

  // ── Multiple Choice (MCQ) ──────────────────────────────────────────────
  stem?: string | null;
  options?: string[] | null;
  correctIndex?: number | null;

  // ── Cloze ──────────────────────────────────────────────────────────────
  clozeText?: string | null;
  clozeChildren?: number[] | null;
  clozeIndex?: number | null;

  // ── Image Occlusion (IO) — shared ─────────────────────────────────────
  /** Optional question prompt written inside an IO block. */
  prompt?: string | null;

  // ── IO parent ──────────────────────────────────────────────────────────
  imageRef?: string | null;
  /** @deprecated Alias for `imageRef`; kept for backwards-compat with older stores. */
  ioSrc?: string | null;
  maskMode?: "solo" | "all" | null;

  // ── IO child ───────────────────────────────────────────────────────────
  parentId?: string;
  groupKey?: string;
  rectIds?: string[];
  retired?: boolean;

  // ── Shared metadata ────────────────────────────────────────────────────
  info?: string | null;
  groups?: string[] | null;

  // ── Source location ────────────────────────────────────────────────────
  sourceNotePath: string;
  sourceStartLine: number;

  // ── Legacy / backward-compat aliases ───────────────────────────────────
  /** @deprecated Legacy alias for `sourceNotePath`. */
  location?: string;
  /** @deprecated Legacy alias for `sourceNotePath`. */
  sourcePath?: string;
  /** @deprecated Legacy anchor reference. */
  anchor?: string;
  /** @deprecated Legacy block ID reference. */
  blockId?: string;
  /** @deprecated Legacy alias for `imageRef`. */
  src?: string;
  /** @deprecated Legacy alias for `imageRef`. */
  image?: string;
  /** @deprecated Legacy alias for `groupKey`. */
  ioGroupKey?: string;
  /** @deprecated Legacy alias for `groupKey`. */
  key?: string;
  /** @deprecated Legacy alias for `info`. */
  information?: string | null;
  /** @deprecated Short alias for `info`. */
  i?: string | null;
  /** @deprecated Short alias for `info`. */
  I?: string | null;
  /** @deprecated Legacy nested fields object. */
  fields?: Record<string, unknown>;

  // ── Bookkeeping (written by sync; optional for older stores) ───────────
  createdAt?: number;
  updatedAt?: number;
  lastSeenAt?: number;
};
