/**
 * @file src/core/default-settings.ts
 * @summary Provides the factory-default values for every Sprout plugin setting. Re-exports
 * the SproutSettings type from src/types/settings.ts so downstream code can import both
 * the type and the defaults from one location. Used to seed fresh installations and to
 * reset settings to factory defaults.
 *
 * @exports
 *   - SproutSettings (re-exported type) — full plugin settings shape
 *   - DEFAULT_SETTINGS — constant object with factory-default values for all settings
 */

// Re-export the type so existing `import { SproutSettings } from "./default-settings"` still works
export type { SproutSettings } from "../types/settings";
import type { SproutSettings } from "../types/settings";

/** Factory-default values for every plugin setting. */
export const DEFAULT_SETTINGS: SproutSettings = {

  general: {
    interfaceLanguage: "en-gb",
    userName: "",
    showGreeting: true,
    hasOpenedHome: false,
    pinnedDecks: [],
    workspaceContentZoom: 1,
    githubStars: {
      count: null,
      fetchedAt: null,
    },
    enableAnimations: true,
    themePreset: "playground",
    themeAccentOverride: "",
    showLaunchNoticeModal: true,
    enableReadingStyles: true,
    prettifyCards: "accent", // default to 'accent', options: 'off' | 'accent' | 'theme'
  },

  study: {
    showInfoByDefault: false,

    dailyNewLimit: 20,
    dailyReviewLimit: 200,

    autoAdvanceEnabled: false,
    autoAdvanceSeconds: 60,

    // DEFAULT = two-button
    fourButtonMode: false,
    showGradeIntervals: true,

    enableSkipButton: false,
    randomizeMcqOptions: true,
    randomizeOqOrder: true,

    siblingMode: "standard" as const,

    treatFolderNotesAsDecks: true,

    analyticsIncludePracticeNoteReview: true,
    analyticsTopicHierarchy: "folder-group-topic",
    analyticsMasteryThresholds: {
      redMax: 59,
      yellowMax: 79,
    },
    analyticsFocusTopicCount: 7,
  },

  studyAssistant: {
    enabled: true,
    location: "modal",
    modalButtonVisibility: "hover",
    voiceChat: false,
    provider: "openai",
    openRouterTier: "free",
    model: "gpt-4.1-mini",
    endpointOverride: "",
    apiKeys: {
      openai: "",
      anthropic: "",
      deepseek: "",
      xai: "",
      google: "",
      perplexity: "",
      openrouter: "",
      custom: "",
    },
    prompts: {
      assistant: "You are a helpful study companion. Use note context first, then supplement with clearly-labeled background knowledge when needed. If I ask for flashcards, format them as parser-compatible rows in a markdown code block and remind me that the Generate key creates context-aware cards I can insert directly.",
      noteReview: "Review this note for correctness, clarity, and exam readiness. Suggest concrete improvements. If I ask for flashcards, format them as parser-compatible rows in a markdown code block and remind me that the Generate key creates context-aware cards I can insert directly.",
      generator: "Generate high-quality flashcards from this note. Avoid duplicates and prioritize testable facts.",
    },
    generatorTypes: {
      basic: true,
      reversed: true,
      cloze: true,
      mcq: true,
      oq: true,
      io: true,
    },
    generatorTargetCount: 5,
    generatorOutput: {
      includeTitle: true,
      includeInfo: true,
      includeGroups: false,
    },
    privacy: {
      autoSendOnOpen: false,
      includeImagesInAsk: true,
      includeImagesInReview: true,
      includeImagesInFlashcard: true,
      includeAttachmentsInCompanion: true,
      includeAttachmentsInExam: true,
      previewPayload: true,
      saveChatHistory: true,
      syncDeletesToProvider: false,
    },
  },

  reminders: {
    showOnStartup: false,
    startupDelayMs: 1000,
    repeatEnabled: false,
    repeatIntervalMinutes: 30,
    gatekeeperEnabled: false,
    gatekeeperOnStartup: false,
    gatekeeperIntervalMinutes: 30,
    gatekeeperDueQuestionCount: 3,
    gatekeeperScope: "workspace",
    gatekeeperPauseWhenStudying: true,
    gatekeeperAllowSkip: false,
    gatekeeperBypassWarning: true,
    showWhenNoDue: false,
    message: "",
    clickAction: "open-home",
  },

  // Reasonable “Balanced” defaults matching your UI copy
  scheduling: {
    learningStepsMinutes: [10, 1440],
    relearningStepsMinutes: [10],
    requestRetention: 0.9,
  },

  noteReview: {
    algorithm: "fsrs",
    enableSessionAnimations: true,
    avoidFolderNotes: true,
    filterQuery: "",
    reviewsPerDay: 10,
    reviewStepsDays: [1, 7, 30, 365],
    fillFromFutureWhenUnderLimit: true,
  },

  cards: {
    clozeMode: "standard",
    clozeBgColor: "",
    clozeTextColor: "",
  },

  indexing: {
    ignoreInCodeFences: true,
    idPlacement: "above",
    delimiter: "|",
  },

  imageOcclusion: {
    defaultMaskMode: "solo",
    revealMode: "group",
    maskTargetColor: "",
    maskOtherColor: "",
    maskIcon: "circle-help",
  },

  readingView: {
    preset: "flashcards",
    advancedEnabled: false,
    layout: "masonry",
    cardMode: "flip",
    visibleFields: {
      title: true,
      question: true,
      options: false,
      answer: true,
      info: false,
      groups: true,
      edit: true,
    },
    displayLabels: true,
    cardBgLight: "",
    cardBgDark: "",
    cardBorderLight: "",
    cardBorderDark: "",
    cardAccentLight: "",
    cardAccentDark: "",
    fontSize: 0.9,
    activeMacro: "flashcards",
    macroConfigs: {
      flashcards: {
        fields: {
          title: false,
          question: true,
          options: false,
          answer: true,
          info: false,
          groups: false,
          edit: false,
          labels: false,
          displayAudioButton: true,
          displayEditButton: true,
        },
        colours: {
          autoDarkAdjust: true,
          cardBgLight: "",
          cardBgDark: "",
          cardBorderLight: "",
          cardBorderDark: "",
          cardAccentLight: "",
          cardAccentDark: "",
          cardTextLight: "",
          cardTextDark: "",
          cardMutedLight: "",
          cardMutedDark: "",
          clozeBgLight: "",
          clozeTextLight: "",
          clozeBgDark: "",
          clozeTextDark: "",
        },
      },
      classic: {
        fields: {
          title: true,
          question: true,
          options: true,
          answer: true,
          info: true,
          groups: true,
          edit: true,
          labels: true,
          displayAudioButton: true,
          displayEditButton: true,
        },
        colours: {
          autoDarkAdjust: true,
          cardBgLight: "",
          cardBgDark: "",
          cardBorderLight: "",
          cardBorderDark: "",
          cardAccentLight: "",
          cardAccentDark: "",
          cardTextLight: "",
          cardTextDark: "",
          cardMutedLight: "",
          cardMutedDark: "",
          clozeBgLight: "",
          clozeTextLight: "",
          clozeBgDark: "",
          clozeTextDark: "",
        },
      },
      guidebook: {
        fields: {
          title: true,
          question: true,
          options: true,
          answer: true,
          info: true,
          groups: true,
          edit: true,
          labels: true,
          displayAudioButton: true,
          displayEditButton: true,
        },
        colours: {
          autoDarkAdjust: true,
          cardBgLight: "",
          cardBgDark: "",
          cardBorderLight: "",
          cardBorderDark: "",
          cardAccentLight: "",
          cardAccentDark: "",
          cardTextLight: "",
          cardTextDark: "",
          cardMutedLight: "",
          cardMutedDark: "",
          clozeBgLight: "",
          clozeTextLight: "",
          clozeBgDark: "",
          clozeTextDark: "",
        },
      },
      markdown: {
        fields: {
          title: true,
          question: true,
          options: true,
          answer: true,
          info: true,
          groups: true,
          edit: false,
          labels: true,
          displayAudioButton: true,
          displayEditButton: false,
        },
        colours: {
          autoDarkAdjust: true,
          cardBgLight: "",
          cardBgDark: "",
          cardBorderLight: "",
          cardBorderDark: "",
          cardAccentLight: "",
          cardAccentDark: "",
          cardTextLight: "",
          cardTextDark: "",
          cardMutedLight: "",
          cardMutedDark: "",
          clozeBgLight: "",
          clozeTextLight: "",
          clozeBgDark: "",
          clozeTextDark: "",
        },
      },
      custom: {
        fields: {
          title: true,
          question: true,
          options: true,
          answer: true,
          info: true,
          groups: true,
          edit: true,
          labels: true,
          displayAudioButton: true,
          displayEditButton: true,
        },
        colours: {
          autoDarkAdjust: true,
          cardBgLight: "",
          cardBgDark: "",
          cardBorderLight: "",
          cardBorderDark: "",
          cardAccentLight: "",
          cardAccentDark: "",
          cardTextLight: "",
          cardTextDark: "",
          cardMutedLight: "",
          cardMutedDark: "",
          clozeBgLight: "",
          clozeTextLight: "",
          clozeBgDark: "",
          clozeTextDark: "",
        },
        customCss: "",
      },
    },
  },

  storage: {
    imageOcclusionFolderPath: "Attachments/Image Occlusion/",
    deleteOrphanedImages: true,
    cardAttachmentFolderPath: "Attachments/Cards/",
    vaultSync: {
      enabled: false,
      folderPath: "LearnKit/",
    },
    backups: {
      rollingDailyEnabled: true,
      recentCount: 8,
      dailyCount: 7,
      weeklyCount: 4,
      monthlyCount: 1,
      recentIntervalHours: 6,
      dailyIntervalDays: 1,
      weeklyIntervalDays: 7,
      monthlyIntervalDays: 30,
      maxTotalSizeMb: 250,
    },
  },

  audio: {
    enabled: false,
    autoplay: true,
    limitToGroup: "",
    basicFront: false,
    basicBack: false,
    widgetReplay: true,
    gatekeeperReplay: false,
    clozeFront: false,
    clozeRevealed: false,
    clozeAnswerMode: "cloze-only" as const,
    defaultLanguage: "en-US",
    autoDetectLanguage: true,
    scriptLanguages: {
      cyrillic: "ru-RU",
      arabic: "ar-SA",
      cjk: "zh-CN",
      devanagari: "hi-IN",
    },
    useFlagsForVoiceSelection: true,
    speakFlagLanguageLabel: false,
    rate: 1.0,
    pitch: 1.0,
    preferredVoiceURI: "",
  },
};
